# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparks.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'sparks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csparks.proto\">\n\x15NextInvocationRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\x12\x11\n\tauthToken\x18\x02 \x01(\x0c\"\x9d\x01\n\x16NextInvocationResponse\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x14\n\x0ctrigger_type\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\x0c\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x12\x14\n\x0ctrigger_data\x18\x07 \x01(\x0c\"\x83\x01\n\x13TaskResponseRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t\x12\x12\n\nInstanceId\x18\x04 \x01(\t\x12\x11\n\tauthToken\x18\x05 \x01(\x0c\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\"\x16\n\x14TaskResponseResponse2\x92\x01\n\x0c\x43ontainerAPI\x12\x43\n\x0eNextInvocation\x12\x16.NextInvocationRequest\x1a\x17.NextInvocationResponse\"\x00\x12=\n\x0cTaskResponse\x12\x14.TaskResponseRequest\x1a\x15.TaskResponseResponse\"\x00\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sparks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_NEXTINVOCATIONREQUEST']._serialized_start=16
  _globals['_NEXTINVOCATIONREQUEST']._serialized_end=78
  _globals['_NEXTINVOCATIONRESPONSE']._serialized_start=81
  _globals['_NEXTINVOCATIONRESPONSE']._serialized_end=238
  _globals['_TASKRESPONSEREQUEST']._serialized_start=241
  _globals['_TASKRESPONSEREQUEST']._serialized_end=372
  _globals['_TASKRESPONSERESPONSE']._serialized_start=374
  _globals['_TASKRESPONSERESPONSE']._serialized_end=396
  _globals['_CONTAINERAPI']._serialized_start=399
  _globals['_CONTAINERAPI']._serialized_end=545
# @@protoc_insertion_point(module_scope)
