# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from anedya_sparks.proto import sparks_pb2 as sparks__pb2

GRPC_GENERATED_VERSION = '1.54.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sparks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.',
        RuntimeWarning
    )


class ContainerAPIStub(object):
    """ContainerAPI gRPC service stub (client side)."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NextInvocation = channel.unary_unary(
            '/ContainerAPI/NextInvocation',
            request_serializer=sparks__pb2.NextInvocationRequest.SerializeToString,
            response_deserializer=sparks__pb2.NextInvocationResponse.FromString,
            _registered_method=True,
        )
        self.TaskResponse = channel.unary_unary(
            '/ContainerAPI/TaskResponse',
            request_serializer=sparks__pb2.TaskResponseRequest.SerializeToString,
            response_deserializer=sparks__pb2.TaskResponseResponse.FromString,
            _registered_method=True,
        )
        # TODO: TaskError stub — add once the RPC is defined in sparks.proto
        # self.TaskError = channel.unary_unary(
        #     '/ContainerAPI/TaskError',
        #     request_serializer=sparks__pb2.TaskErrorRequest.SerializeToString,
        #     response_deserializer=sparks__pb2.TaskErrorResponse.FromString,
        #     _registered_method=True,
        # )


class ContainerAPIServicer(object):
    """ContainerAPI gRPC service servicer (server side — for testing only)."""

    def NextInvocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    # TODO: TaskError servicer method
    # def TaskError(self, request, context):
    #     context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    #     context.set_details('Method not implemented!')
    #     raise NotImplementedError('Method not implemented!')


def add_ContainerAPIServicer_to_server(servicer, server):
    from grpc import experimental
    rpc_method_handlers = {
        'NextInvocation': grpc.unary_unary_rpc_method_handler(
            servicer.NextInvocation,
            request_deserializer=sparks__pb2.NextInvocationRequest.FromString,
            response_serializer=sparks__pb2.NextInvocationResponse.SerializeToString,
        ),
        'TaskResponse': grpc.unary_unary_rpc_method_handler(
            servicer.TaskResponse,
            request_deserializer=sparks__pb2.TaskResponseRequest.FromString,
            response_serializer=sparks__pb2.TaskResponseResponse.SerializeToString,
        ),
        # TODO: TaskError handler — add once the RPC is defined
    }
    generic_handler = grpc.method_service_handler('ContainerAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ContainerAPI', rpc_method_handlers)


class ContainerAPI(object):
    """ContainerAPI gRPC service definition (for experimental API)."""

    @staticmethod
    def NextInvocation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ContainerAPI/NextInvocation',
            sparks__pb2.NextInvocationRequest.SerializeToString,
            sparks__pb2.NextInvocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TaskResponse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ContainerAPI/TaskResponse',
            sparks__pb2.TaskResponseRequest.SerializeToString,
            sparks__pb2.TaskResponseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
